### ISSUE TITLE
Error when build with version 3.3.0

### ISSUE THREAD

**Issue by ufgo** [AGulev/defold-poki-sdk#28]
```
The build failed for the following reasons:

ERROR: poki-sdk/src/pokisdk.cpp:104: 'use of undeclared identifier 'dmSound'
  104 |         dmSound::SetGroupMute(MASTER_SOUND_GROUP, false);'

ERROR: poki-sdk/src/pokisdk.cpp:121: 'use of undeclared identifier 'dmSound'
  121 |     dmSound::SetGroupMute(MASTER_SOUND_GROUP, true);'

ERROR: poki-sdk/src/pokisdk.cpp:127: 'use of undeclared identifier 'dmSound'
  127 |     dmSound::SetGroupMute(MASTER_SOUND_GROUP, true);'

ERROR: poki-sdk/src/pokisdk.cpp:104: 'use of undeclared identifier 'dmSound'
  104 |         dmSound::SetGroupMute(MASTER_SOUND_GROUP, false);'

ERROR: poki-sdk/src/pokisdk.cpp:121: 'use of undeclared identifier 'dmSound'
  121 |     dmSound::SetGroupMute(MASTER_SOUND_GROUP, true);'

ERROR: poki-sdk/src/pokisdk.cpp:127: 'use of undeclared identifier 'dmSound'
  127 |     dmSound::SetGroupMute(MASTER_SOUND_GROUP, true);'

ERROR: poki-sdk/src/pokisdk.cpp:104: 'use of undeclared identifier 'dmSound'
  104 |         dmSound::SetGroupMute(MASTER_SOUND_GROUP, false);'

ERROR: poki-sdk/src/pokisdk.cpp:121: 'use of undeclared identifier 'dmSound'
  121 |     dmSound::SetGroupMute(MASTER_SOUND_GROUP, true);'

ERROR: poki-sdk/src/pokisdk.cpp:127: 'use of undeclared identifier 'dmSound'
  127 |     dmSound::SetGroupMute(MASTER_SOUND_GROUP, true);'

```
